### ISSUE TITLE
[bug] Clipping text on box on mobile

### ISSUE THREAD

**Issue by micwoj92** [mastercomfig/comfig-app#10]
While I understand that this is a niche use case and mastercomfig is intended for computer this is still a bug.
![Screenshot_20200617_032641_org mozilla fennec_fdroid](https://user-images.githubusercontent.com/45581170/84844375-7da11a80-b04a-11ea-8a2a-0e6aa0bc7c51.jpg)

**Comment by mastercoms** [comment]
It will probably need text size changes, globally or based on screen size.
