### ISSUE TITLE
Setup dependabot?

### ISSUE THREAD

**Issue by micwoj92** [mastercomfig/comfig-app#11]
It's free and could easily automate updating jquery, poppler.js etc. 

https://github.com/marketplace/dependabot-preview

**Comment by mastercoms** [comment]
Dependabot does not support how we manage dependencies. And we already have automatic updating for point releases on dependencies, through jsdelivr.

See here: https://github.com/mastercomfig/mastercomfig.github.io/blob/master/index.html#L225
