### ISSUE TITLE
Offline page not working :(

### ISSUE THREAD

**Issue by hipocentrum** [mastercomfig/comfig-app#27]
Hello, I save the download app(lication) 
![image](https://user-images.githubusercontent.com/83860982/121519138-a22b9a80-c9f1-11eb-88e7-3fe06312f26b.png)

1. Right click
![image](https://user-images.githubusercontent.com/83860982/121519265-cdae8500-c9f1-11eb-8ac7-e507ca56f712.png)

2. Save as
![image](https://user-images.githubusercontent.com/83860982/121519301-d8691a00-c9f1-11eb-9ee6-c51e06a9deab.png)

3. save mastercomfig.html HTML document (it's webpage)
![image](https://user-images.githubusercontent.com/83860982/121519421-fc2c6000-c9f1-11eb-8d94-a41c96b7da43.png)
![image](https://user-images.githubusercontent.com/83860982/121519462-077f8b80-c9f2-11eb-9f60-0a7af7a5747e.png)

4. open mastercomfig.html file in browser
![image](https://user-images.githubusercontent.com/83860982/121519006-75778300-c9f1-11eb-85c1-a3f1fe276f1c.png)
![image](https://user-images.githubusercontent.com/83860982/121519064-8aecad00-c9f1-11eb-8355-f93bbfee5c94.png)
:frowning_face: :-1: 
5. mastercomfig 7 was better
![image](https://user-images.githubusercontent.com/83860982/121519647-3d247480-c9f2-11eb-9d25-c40abff5fc6c.png)
:smiley: :+1:

**Comment by mastercoms** [comment]
This is not the intended use case for using the app's offline mode. You can visit https://mastercomfig.com/app while offline; you do not need to save the page. Also, offline support has been work in progress, though I think I am done with it as of a minute or two ago. Are you sure you have tested the latest changes?

**Comment by hipocentrum** [comment]
I can't visit the page while offline, I get dinosaur. How to test latest change?

**Comment by mastercoms** [comment]
Make sure you clear your cache with a hard refresh (click the refresh button while holding shift), then refresh the page one more time normally to do a normal page visit, to make sure the service worker is properly installed. If it still does not work, can you tell me your browser + browser version?

**Comment by hipocentrum** [comment]
![image](https://user-images.githubusercontent.com/83860982/121521139-fc2d5f80-c9f3-11eb-8acb-60ed6b7afdbc.png)

Not work, FireFox 78.11.0esr (64-bit)

**Comment by mastercoms** [comment]
Do you have service workers enabled (`about:config` > `dom.serviceWorkers.enabled`)? They should be enabled by default starting in 78, not sure why it is not working for you.

**Comment by hipocentrum** [comment]
Yes
![image](https://user-images.githubusercontent.com/83860982/121521514-75c54d80-c9f4-11eb-8704-ce72f7dc7454.png)
![image](https://user-images.githubusercontent.com/83860982/121521604-91305880-c9f4-11eb-9d1a-63499849deca.png)

**Comment by hipocentrum** [comment]
With internet working, page work.  I will use page online. 
![image](https://user-images.githubusercontent.com/83860982/121521832-cccb2280-c9f4-11eb-8db4-958e8ffdca03.png)

**Comment by hipocentrum** [comment]
I think INTERNET browser should be made for online. Thank you for effort but for offline just make application, not webpage. :+1:

**Comment by mastercoms** [comment]
![image](https://user-images.githubusercontent.com/2672245/121521940-9ffe1780-c9c2-11eb-80cb-3dce5b9e2a43.png)

Can you check developer tools (F12) in the Application tab, and show me?

**Comment by mastercoms** [comment]
> I think INTERNET browser should be made for online. Thank you for effort but for offline just make application, not webpage. 👍

I don't agree. The web is a platform, just like native. Also, mastercomfig 7 used Electron, so it used web technologies as well. It is a better option in my opinion to have the app work transparently with no true install, where Electron can add bloat as Electron is a separate Chrome installation for each app. PWA is a rapidly growing field, and I can take advantage of many technologies which will make this new app work better for the user than any native web API.

**Comment by hipocentrum** [comment]
> ![image](https://user-images.githubusercontent.com/2672245/121521940-9ffe1780-c9c2-11eb-80cb-3dce5b9e2a43.png)
> 
> Can you check developer tools (F12) in the Application tab, and show me?

I don't see application...
![image](https://user-images.githubusercontent.com/83860982/121522357-511da580-c9f5-11eb-8db5-02167e00fe9a.png)

**Comment by hipocentrum** [comment]
> > I think INTERNET browser should be made for online. Thank you for effort but for offline just make application, not webpage. +1
> 
> I don't agree. The web is a platform, just like native. Also, mastercomfig 7 used Electron, so it used web technologies as well. It is a better option in my opinion to have the app work transparently with no true install, where Electron can add bloat as Electron is a separate Chrome installation for each app. PWA is a rapidly growing field, and I can take advantage of many technologies which will make this new app work better for the user than any native web API.

But I liked the mastercomfig 7. Can be made this webpage using electron?

**Comment by mastercoms** [comment]
![image](https://user-images.githubusercontent.com/2672245/121522430-1a2e9c00-c9c3-11eb-8581-36ca6d909bfb.png)

Maybe you need to enable it in settings? If not, then maybe your browser version does not support these technologies yet. I can provide a native wrapper to the new app, but I think there is little point to that vs. the user downloading a separate browser installation like Chrome or the latest Firefox and using the app from there, since Electron is technically a distribution of Chrome anyway.

**Comment by hipocentrum** [comment]
Here the worker, it say it work (now I am online)
![image](https://user-images.githubusercontent.com/83860982/121522808-c8533980-c9f5-11eb-8b45-51ee250fb46a.png)




> but I think there is little point to that vs. the user downloading a separate browser installation like Chrome or the latest Firefox 

I was used latest firefox but not like the UI, I will use the ESR version and when it breaks because no updates... I don't know what to do. I want good FireFox.

**Comment by hipocentrum** [comment]
OK, now I reboot my browser and it work.

**Comment by hipocentrum** [comment]
Thank you for assist, but I will use page online. I need online to play tf2. No point to use offline because tf2 is best online with team.

**Comment by hipocentrum** [comment]
Can I add you on steam to play tf2 with mastercomfig?

**Comment by mastercoms** [comment]
> I was used latest firefox but not like the UI, I will use the ESR version and when it breaks because no updates... I don't know what to do. I want good FireFox.

Yeah, I meant that you could use a separate browser installation for the app exclusively, since you'd be doing that anyway with Electron. Glad you could get it working. I understand that offline support might not be the most useful, but it does help for unstable connections, and gets it passing as an app, as the UI is available offline.

**Comment by hipocentrum** [comment]
> Can I add you on steam to play tf2 with mastercomfig?

My name on steam is thelegend27, this issue name is 27 XD

**Comment by hipocentrum** [comment]
I can't add you. Says error, I am level 0...
