### ISSUE TITLE
Hide "Choose your Team Fortress 2 installation folder" behind a checkbox called "Direct Instalation"

### ISSUE THREAD

**Issue by Kenajcrap** [mastercomfig/comfig-app#31]
Newbie users often get stuck while downloading mastercomfig because of the whole "you need to have your library outside a system folder" thing going way over their heads. A way to prevent this is to make sure that the user does want to use the direct install feature before showing the warning that asks them to move their steam library. This also prevents people from thinking that it's a requirement to use mastercomfig.

Furthermore, I think that when the checkbox is enabled, the 2 download buttons for the preset and customization respectively could be switched to a single one that downloads everything, since the reason for the separate downloads (being that each one needs to be sent to a different folder) is not really applicable anymore.

Wording on the warning could also be improved from "Please move Steam" to "Please move your Steam Library" since the link points to a page where the first step by step is to move the steam library, not the steam installation, and is probably what the user should prefer to do anyways. Besides that, the sentence "If you do not wish to do either, download the files without choosing a folder." could be changed to "If you do not wish to do either, you can disable the checkbox and proceed with the manual installation." given the whole checkbox thing.

**Comment by mastercoms** [comment]
Fixed in 14e1a1a180e8343e00632b021e011a0e5b91e901.

![Direct Install checkbox](https://user-images.githubusercontent.com/2672245/158042416-0b7dba21-9c88-4485-a95c-de7d3dde99c1.png)
