### ISSUE TITLE
Ping tolerance link

### ISSUE THREAD

**Issue by Tiagoquix** [mastercomfig/comfig-app#35]
In https://mastercomfig.com/app, when clicking in the "read the docs" icon for the Ping Tolerance module it doesn't work since it redirects to `https://docs.mastercomfig.com/page/customization/modules/#ping-tolerance-(matchmaking)`. The correct link is `https://docs.mastercomfig.com/page/customization/modules/#ping-tolerance-matchmaking`. Could you make it so it redirects correctly?

Thanks in advance.

**Comment by mastercoms** [comment]
Fixed in 531473b45c75780ad2772f730716ff3c634a4d2d
