### ISSUE TITLE
Suggestion: change "Click to copy" color when hovering over it

### ISSUE THREAD

**Issue by Tiagoquix** [mastercomfig/comfig-app#36]
There's no indication that the button appears to actually work. Adding something like a gray color when hovering over it would be nice.
![image](https://user-images.githubusercontent.com/30274161/162558416-119404aa-859e-45ba-b439-ceb1eb18fb8a.png)

Again, thanks in advance.

**Comment by mastercoms** [comment]
you click the launch options preferably, in order to copy them but then you see theyre copied. every part of it works just in case and theres no click mouse icon because its meant to be text
