### ISSUE TITLE
Change download button text

### ISSUE THREAD

**Issue by Tiagoquix** [mastercomfig/comfig-app#37]
"Download Ultra preset and selected addons" -> "Download Ultra preset, selected addons and customizations" or "Download selected preset, addons and customizations".

I think it would be better this way.

**Comment by mastercoms** [comment]
I've wanted to do this for a while, but the logic for managing the text is a bit more complicated than one would expect, so I've been holding off on it. One day, we may have the technology to achieve this...

**Comment by mastercoms** [comment]
Fixed in 81d810ce05252c52f2ad5db664bc947436b0a252
