### ISSUE TITLE
"Click to copy" button copies `undefined` to the clipboard

### ISSUE THREAD

**Issue by ghost** [mastercomfig/comfig-app#38]
Hi. When I go to https://mastercomfig.com/app/ and click "Click to copy" under Launch Options, all that gets copied to my clipboard is `undefined`. I'm using Firefox 100.0.2 on Linux

**Comment by mastercoms** [comment]
I really appreciate the report, I'm not exactly sure why it broke, but it's fixed now!

**Comment by mastercoms** [comment]
Ah, it's because I reformatted the HTML, it added a space. I love HTML!
