### ISSUE TITLE
Do not use non-standard `::-webkit-scrollbar` pseudo element

### ISSUE THREAD

**Issue by micwoj92** [mastercomfig/comfig-app#44]
https://github.com/mastercomfig/comfig-app/blob/9981a7900c064af0005f0eb10a144438407ce32b/src/styles/global.scss#L17

I believe that using non-standards that are not supported in Firefox is hurting web. Target browser supported should be at least latest Firefox ESR.

**Comment by getchoo** [comment]
better yet, at least netscape navigator 9

**Comment by micwoj92** [comment]
https://www.netsurf-browser.org/
