### ISSUE TITLE
[request] Add button to toggle addons download

### ISSUE THREAD

**Issue by micwoj92** [mastercomfig/comfig-app#5]
Toggle to mark/unmark all addons to download could be nice feature.

**Comment by mastercoms** [comment]
What's the use case of toggling addons?

**Comment by micwoj92** [comment]
It just would be faster than clicking them one after one.

**Comment by mastercoms** [comment]
When would you need to click on all of them?

**Comment by micwoj92** [comment]
When I want to download all addons.

**Comment by mastercoms** [comment]
Why would you want to download them all, indiscriminately? I feel like a user would make a choice per addon, and if it so happens that they feel like each and every one is for them, then that's done after they decide per addon.

**Comment by micwoj92** [comment]
Really bad pc? Or maybe testing. Also when there are addons selected by default when clicking low or very low, then it is faster to click one button to toggle these to not be downloaded.

**Comment by mastercoms** [comment]
I don't think it would be valuable for the extra UI element and distraction from main flow.
