### ISSUE TITLE
unable to bind side mouse buttons

### ISSUE THREAD

**Issue by ghost** [mastercomfig/comfig-app#56]
in the binds section of the web app the side buttons of the mouse don't register as key presses and therefore cannot be binded to any action.

**Comment by mastercoms** [comment]
What browser?

**Comment by ghost** [comment]
firefox 120, running fedora 39

**Comment by mastercoms** [comment]
Yep, I can confirm that Firefox now specifically overrides the side mouse buttons for navigation. On Chrome, the behavior is still as expected. I will look into workarounds.

**Comment by mastercoms** [comment]
Fixed this and also discovered that mouse4 and mouse5 were flipped!
