### ISSUE TITLE
Erroneous "browser out of date" message for Firefox ESR

### ISSUE THREAD

**Issue by 0CCULTIST** [mastercomfig/comfig-app#60]
![image](https://github.com/mastercomfig/comfig-app/assets/150618116/e885e17b-5252-4e34-a0c7-bdee9db21f0c)

Firefox ESR 115 is the most up to date in Debian repos. It isn't a security concern.

**Comment by mastercoms** [comment]
Anything that is too behind the latest version will be marked as out of date. That includes ESR, which does not receive feature patches for new JavaScript features which the site requires often. There were many times where ESR was stuck on a version for months which did not support a feature needed for the site's operation.
