### ISSUE TITLE
Comfig-App crashes Steamwebhelper

### ISSUE THREAD

**Issue by rcmaehl** [mastercomfig/comfig-app#62]
I didn't think it be like it is, but it do

How can I spread the good word of mastercomfig to people via steam chat if it crashes them :(

https://github.com/mastercomfig/comfig-app/assets/716581/037770d9-0b9d-48f4-91e4-5ceadc9f1fc8

**Comment by mastercoms** [comment]
I think it has to do with the service worker, I'm starting to remember why I had disabled it in the first place!

**Comment by mastercoms** [comment]
Is this still happening?

**Comment by rcmaehl** [comment]
> Is this still happening?

I will check first thing tomorrow

**Comment by rcmaehl** [comment]
I can confirm it's fixed, but not before one last crash from the cached page 😂
