### ISSUE TITLE
Interface not fully visible when on vertical monitor/tall screen

### ISSUE THREAD

**Issue by matthew-rimmer** [mastercomfig/comfig-app#65]
![image](https://github.com/mastercomfig/comfig-app/assets/40692294/13e03894-2cdf-403a-9e58-b343d64e55d4)

Happy to take a look fixing this myself and PRing it?

**Comment by mastercoms** [comment]
Sure feel free but I can also look into it

**Comment by mastercoms** [comment]
What's your exact screen resolution? Because I can't reproduce this at the moment
